# Generated by Django 4.1.4 on 2022-12-22 15:38

import Room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=Room.models.generate_unique_code, max_length=8, unique=True)),
                ('host', models.CharField(max_length=100)),
                ('exam', models.CharField(blank=True, max_length=100)),
                ('test', models.CharField(blank=True, max_length=100)),
                ('time', models.IntegerField(default=60)),
                ('paragraph', models.TextField()),
                ('criteria', models.TextField()),
                ('teacher', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
