# Generated by Django 4.1.4 on 2022-12-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_alter_room_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='student',
        ),
    ]
