# Generated by Django 4.1.4 on 2022-12-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0004_remove_performance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='teacher',
        ),
    ]
