# Generated by Django 4.1.4 on 2022-12-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0007_remove_room_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='isExpired',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
