# Generated by Django 4.1.4 on 2023-01-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0008_room_isexpired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='test',
        ),
        migrations.AddField(
            model_name='room',
            name='test_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='test_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
