# Generated by Django 4.1.4 on 2023-01-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0009_remove_room_test_room_test_id_room_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='student',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
