# Generated by Django 4.1.4 on 2023-01-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0010_performance_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
