# Generated by Django 4.1.4 on 2023-01-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0011_delete_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='paragraphText',
            field=models.TextField(null=True),
        ),
    ]
