# Generated by Django 4.1.4 on 2022-12-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='attempts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
