# Generated by Django 4.1.4 on 2022-12-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_tests_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='attempts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
