# Generated by Django 4.1.4 on 2023-01-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_tests_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='ratings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
