# Generated by Django 4.1.4 on 2023-01-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exams_user_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='ratings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
