# Generated by Django 4.1.4 on 2023-01-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exams_rating_alter_exams_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
