# Generated by Django 4.1.4 on 2023-01-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_alter_exams_user_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
