# Generated by Django 4.1.4 on 2022-12-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('institute', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
