# Generated by Django 4.1.4 on 2022-12-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='board',
            field=models.CharField(default='CBSE', max_length=100, null=True),
        ),
    ]
