# Generated by Django 4.1.4 on 2022-12-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0003_alter_user_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
