# Generated by Django 4.1.4 on 2022-12-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0004_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
