# Generated by Django 4.1.4 on 2022-12-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0005_user_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
