# Generated by Django 4.1.4 on 2023-01-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0008_user_facebook_url_user_instagram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='facebook_url',
            new_name='facebookURL',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='instagram_url',
            new_name='instagramURL',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telegram_url',
            new_name='telegramURL',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='website_url',
            new_name='websiteURL',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='youtube_url',
            new_name='youtubeURL',
        ),
    ]
