# Generated by Django 4.1.4 on 2023-01-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0010_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='accuracy',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='cpm',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='wpm',
            field=models.FloatField(default=None, null=True),
        ),
    ]
