# Generated by Django 4.1.4 on 2022-12-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0002_alter_request_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
